CREATE TABLE WINNER2 
(YEARS INT NOT NULL,SUBJECTS VARCHAR(30) NOT NULL,WINNERS VARCHAR(30),COUNTRY VARCHAR(30),CATEGORY VARCHAR(30),
);
INSERT INTO WINNER2
	(YEARS,SUBJECTS,WINNERS,COUNTRY,CATEGORY)
VALUES
(1970,'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),(1970,'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),(1970,'CHEMISTRY','LUIS FEDERICO LELOIR','FRANCE','SCIENTIST'),(1970,'PHYSIOLOGY','UFF VON EULER','SWEDEN','SCIENTIST'),(1970,'PHYSIOLOGY','BERNARD KATZ','GERMANY','SCIENTIST'),(1970,'LITERATURE','ALEKSANDR SOLZHENITSY','RUSSIA','LINGUIST'),(1970,'ECONOMICS','PAUL SAMUELSON','USA','ECONOMIST'),(1970,'PHYSIOLOGY','JULIUS AELORD','USA','SCIENTIST'),(1971,'PHYSICS','DENNIS GABOR','HUNGARY','SCIENTIST'),(1971,'CHEMISTRY','GERHARD HERZBERG','GERMANY','SCIENTIST'),(1971,'PEACE','WILLY BRANDT','GERMANY','CHANCELLOR'),(1971,'LITERATURE','PABOLA NERUDA','CHILE','LINGUIST'),(1971,'ECONOMICS','SIMON KUZNETS','RUSSIA','ECONOMIST'),(1978,'PEACE','ANWAR AL SADAT','EGYPT','PRESIDENT'),(1978,'PEACE','MENACHEM BEGIN','ISAREL','PRIME MINISTER'),(1987,'CHEMISTRY','DONALD J CRAM','USA','SCIENTIST'),(1987,'CHEMISTRY','JEAN-MARINE LEHN','FRANCE','SCIENTIST'),(1987,'PHYSIOLOGY','SUSUMU TONEGAWA','JAPAN','SCIENTIST'),(1994,'ECONOMICS','REINHARD SELTAN','GERMANY','ECONOMIST'),(1994,'PEACE','YITZHAK RABIN','ISAREL','PRIME MINISTER'),(1987,'PHYSICS','JOHANNES GEORG BEDNORZ','GERMANY','SCIENTIST'),(1987,'LITERATURE','JOSEPH BRODSKY','RUSSIA','LINGUIST'),(1987,'ECONOMICS','ROBRT SOLOW','USA','ECONOMIST'),(1994,'LITERATURE','KENZABURO OE','JAPAN','LINGUIST');

SELECT WINNERS FROM WINNER2
WHERE SUBJECTS ='LITERATURE' AND YEARS=1970;

SELECT WINNERS,YEARS,SUBJECTS FROM WINNER2
WHERE YEARS=1971;

SELECT YEARS,SUBJECTS FROM WINNER2 WHERE WINNERS='DENNIS GABOR';

SELECT WINNERS FROM WINNER2
WHERE SUBJECTS='PHYSICS' AND YEARS>=1950;

SELECT * FROM WINNER2
WHERE SUBJECTS NOT LIKE 'P%'
ORDER BY YEARS DESC,WINNERS ASC;