# -*- coding: utf-8 -*-
"""exercise1 solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-EnNQInNd8gIfFGb0FCIThFcxuiNeKc

1. Write a program to iterate the first 10 numbers and in each iteration, print the sum of the current and previous number.
"""

print('printing the sum of current and previous number in the range(10)')
prev_num=0
for i in range(0,10):
  a_sum=prev_num+i
  print('current_num',i,'prev_num',prev_num,'sum:', prev_num+i)
  prev_num=i

"""2. Write a program to accept a string from the user and display characters that are present at an even index number."""

word = 'niyatig'
print("Original String:", word)
x = list(word)
for i in x[0::2]:
    print(i)

"""3. Iterate the given list of numbers and print only those numbers which are divisible by 5"""

num=[10,20,46,55,33]
print('givenlist:',num)
print('divisible by 5:')
for i in num:
  if i%5==0:
    print(i)

"""4. Write a program to check if the given number is a palindrome number."""

num=545
temp=num
rev=0
while(num>0):
    dig=num%10
    rev=rev*10+dig
    num=num//10
if(temp==rev):
    print("The number is palindrome!")
else:
    print("Not a palindrome!")

"""5. Given a two list of numbers, write a program to create a new list such that the new list should contain odd numbers from the first list and even numbers from the second list."""

list1=[11,22,34,57,44]
listOdd= []
listEven= []
for num in list1:
  if num%2==0:
    listEven.append(num)
  else:
    listOdd.append(num)
print('list1 :', list1)
print('listEven :',listEven)
print('listOdd :',listOdd)

"""6. Write a Program to extract each digit from an integer in the reverse order."""

number = 7536
print("Given number", number)
while number > 0:
  digit = number % 10
  number = number // 10
  print(digit, end=" ")

"""7. Print multiplication table form 1 to 10"""

for i in range(1, 11):
    for j in range(1, 11):
        print(i * j, end=" ")
    print("\t\t")

"""8. Write a program to print downward Half-Pyramid Pattern with Star (asterisk)


"""

for i in range(6, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print(" ")